[opener]
swain-open = [
  { run = 'open %s', orphan = true, desc = "Open", for = "macos" },
  { run = 'xdg-open %s', orphan = true, desc = "Open", for = "linux" },
  { run = 'start "" %*', orphan = true, desc = "Open", for = "windows" },
]

[open]
prepend_rules = [
  { mime = "text/*", use = "swain-open" },
  { mime = "application/{json,ndjson}", use = "swain-open" },
  { mime = "*/javascript", use = "swain-open" },
  { mime = "inode/empty", use = "swain-open" },
  { mime = "*/*", use = "swain-open" },
]
