"""Tests for scoped roadmap generation (SPEC-143)."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from specgraph.roadmap import (
    _compute_descendants,
    _get_children,
    collect_roadmap_items,
    render_scoped_roadmap,
    _write_scoped_slice,
    _write_all_slices,
)


def _make_scoped_graph():
    """Graph with Vision -> Initiative -> Epic -> Spec hierarchy."""
    nodes = {
        "VISION-001": {"type": "Vision", "title": "Core Platform", "status": "Active", "priority_weight": "high", "file": "docs/vision/Active/(VISION-001)-Core/v.md", "brief_description": ""},
        "INITIATIVE-001": {"type": "Initiative", "title": "Auth System", "status": "Active", "file": "docs/initiative/Active/(INITIATIVE-001)-Auth/i.md", "brief_description": "Harden authentication"},
        "INITIATIVE-002": {"type": "Initiative", "title": "Observability", "status": "Active", "file": "docs/initiative/Active/(INITIATIVE-002)-Obs/i.md", "brief_description": ""},
        "EPIC-001": {"type": "Epic", "title": "Login Flow", "status": "Active", "file": "docs/epic/Active/(EPIC-001)-Login/e.md"},
        "EPIC-002": {"type": "Epic", "title": "SSO", "status": "Active", "file": "docs/epic/Active/(EPIC-002)-SSO/e.md"},
        "SPEC-001": {"type": "Spec", "title": "Login API", "status": "Complete", "file": "docs/spec/Complete/(SPEC-001)-Login-API/s.md"},
        "SPEC-002": {"type": "Spec", "title": "Login UI", "status": "Active", "file": "docs/spec/Active/(SPEC-002)-Login-UI/s.md"},
        "SPEC-DIRECT": {"type": "Spec", "title": "Direct Spec", "status": "Active", "file": "docs/spec/Active/(SPEC-003)-Direct/s.md"},
    }
    edges = [
        {"from": "INITIATIVE-001", "to": "VISION-001", "type": "parent-vision"},
        {"from": "INITIATIVE-002", "to": "VISION-001", "type": "parent-vision"},
        {"from": "EPIC-001", "to": "INITIATIVE-001", "type": "parent-initiative"},
        {"from": "EPIC-002", "to": "INITIATIVE-001", "type": "parent-initiative"},
        {"from": "SPEC-001", "to": "EPIC-001", "type": "parent-epic"},
        {"from": "SPEC-002", "to": "EPIC-001", "type": "parent-epic"},
        {"from": "SPEC-DIRECT", "to": "INITIATIVE-001", "type": "parent-initiative"},
    ]
    return nodes, edges


def test_compute_descendants_vision():
    nodes, edges = _make_scoped_graph()
    desc = _compute_descendants("VISION-001", edges)
    assert "INITIATIVE-001" in desc
    assert "INITIATIVE-002" in desc
    assert "EPIC-001" in desc
    assert "EPIC-002" in desc
    assert "SPEC-001" in desc
    assert "SPEC-002" in desc
    assert "SPEC-DIRECT" in desc
    assert "VISION-001" in desc


def test_compute_descendants_initiative():
    nodes, edges = _make_scoped_graph()
    desc = _compute_descendants("INITIATIVE-001", edges)
    assert "EPIC-001" in desc
    assert "EPIC-002" in desc
    assert "SPEC-001" in desc
    assert "SPEC-DIRECT" in desc
    assert "INITIATIVE-001" in desc
    assert "INITIATIVE-002" not in desc
    assert "VISION-001" not in desc


def test_scope_vision_filters_to_subtree():
    nodes, edges = _make_scoped_graph()
    items = collect_roadmap_items(nodes, edges, scope="VISION-001")
    item_ids = {i["id"] for i in items}
    assert "INITIATIVE-001" in item_ids
    assert "EPIC-001" in item_ids
    assert len(items) > 0


def test_scope_initiative_filters_to_children():
    nodes, edges = _make_scoped_graph()
    items = collect_roadmap_items(nodes, edges, scope="INITIATIVE-001")
    item_ids = {i["id"] for i in items}
    assert "EPIC-001" in item_ids
    assert "EPIC-002" in item_ids
    assert "SPEC-DIRECT" in item_ids
    assert "INITIATIVE-002" not in item_ids


def test_scope_excludes_resolved():
    """Scoped collection still skips resolved (Complete) artifacts."""
    nodes, edges = _make_scoped_graph()
    items = collect_roadmap_items(nodes, edges, scope="INITIATIVE-001")
    item_ids = {i["id"] for i in items}
    # SPEC-001 is Complete — it should NOT appear as a roadmap item
    assert "SPEC-001" not in item_ids


def test_scope_invalid_id_returns_empty():
    nodes, edges = _make_scoped_graph()
    items = collect_roadmap_items(nodes, edges, scope="NONEXISTENT-999")
    assert items == []


# --- render_scoped_roadmap tests ---

def test_render_scoped_roadmap_vision():
    nodes, edges = _make_scoped_graph()
    md = render_scoped_roadmap("VISION-001", nodes, edges, repo_root="/tmp/test")
    assert "<!-- Auto-generated by chart.sh roadmap --scope" in md
    assert "VISION-001" in md
    assert "Core Platform" in md
    assert "## Children" in md
    assert "## Progress" in md
    assert "## Recent Activity" in md


def test_render_scoped_roadmap_initiative_with_brief_description():
    nodes, edges = _make_scoped_graph()
    md = render_scoped_roadmap("INITIATIVE-001", nodes, edges, repo_root="/tmp/test")
    assert "Harden authentication" in md
    assert "{{INTENT:" not in md


def test_render_scoped_roadmap_vision_without_brief_description():
    nodes, edges = _make_scoped_graph()
    md = render_scoped_roadmap("VISION-001", nodes, edges, repo_root="/tmp/test")
    assert "{{INTENT: VISION-001}}" in md


def test_render_scoped_roadmap_children_table():
    nodes, edges = _make_scoped_graph()
    md = render_scoped_roadmap("INITIATIVE-001", nodes, edges, repo_root="/tmp/test")
    assert "EPIC-001" in md
    assert "Login Flow" in md
    assert "EPIC-002" in md


# --- _write_scoped_slice tests ---

def test_write_scoped_slice_creates_file(tmp_path):
    nodes, edges = _make_scoped_graph()
    art_dir = tmp_path / "docs" / "initiative" / "Active" / "(INITIATIVE-001)-Auth"
    art_dir.mkdir(parents=True)
    (art_dir / "(INITIATIVE-001)-Auth.md").write_text("---\ntitle: Auth\n---\n# Auth")
    nodes["INITIATIVE-001"]["file"] = str(
        (art_dir / "(INITIATIVE-001)-Auth.md").relative_to(tmp_path)
    )
    _write_scoped_slice("INITIATIVE-001", nodes, edges, str(tmp_path))
    roadmap_file = art_dir / "roadmap.md"
    assert roadmap_file.exists()
    assert "Auto-generated by chart.sh roadmap --scope" in roadmap_file.read_text()


def test_write_scoped_slice_backs_up_manual_roadmap(tmp_path):
    nodes, edges = _make_scoped_graph()
    art_dir = tmp_path / "docs" / "initiative" / "Active" / "(INITIATIVE-001)-Auth"
    art_dir.mkdir(parents=True)
    (art_dir / "(INITIATIVE-001)-Auth.md").write_text("---\ntitle: Auth\n---\n# Auth")
    nodes["INITIATIVE-001"]["file"] = str(
        (art_dir / "(INITIATIVE-001)-Auth.md").relative_to(tmp_path)
    )
    manual = art_dir / "roadmap.md"
    manual.write_text("# My hand-written roadmap\n\nThis is manual content.")
    _write_scoped_slice("INITIATIVE-001", nodes, edges, str(tmp_path))
    backup = art_dir / "roadmap.manual-backup.md"
    assert backup.exists()
    assert "hand-written" in backup.read_text()
    assert "Auto-generated" in manual.read_text()


def test_write_scoped_slice_no_backup_for_generated(tmp_path):
    nodes, edges = _make_scoped_graph()
    art_dir = tmp_path / "docs" / "initiative" / "Active" / "(INITIATIVE-001)-Auth"
    art_dir.mkdir(parents=True)
    (art_dir / "(INITIATIVE-001)-Auth.md").write_text("---\ntitle: Auth\n---\n# Auth")
    nodes["INITIATIVE-001"]["file"] = str(
        (art_dir / "(INITIATIVE-001)-Auth.md").relative_to(tmp_path)
    )
    generated = art_dir / "roadmap.md"
    generated.write_text("<!-- Auto-generated by chart.sh roadmap --scope. Do not edit. -->\n# old")
    _write_scoped_slice("INITIATIVE-001", nodes, edges, str(tmp_path))
    assert not (art_dir / "roadmap.manual-backup.md").exists()


def test_write_all_slices(tmp_path):
    nodes, edges = _make_scoped_graph()
    for aid, node in nodes.items():
        if node.get("type", "").upper() in ("VISION", "INITIATIVE"):
            fpath = node.get("file", "")
            if fpath:
                full = tmp_path / fpath
                full.parent.mkdir(parents=True, exist_ok=True)
                full.write_text(f"---\ntitle: {node['title']}\n---\n# {node['title']}")
    count = _write_all_slices(nodes, edges, str(tmp_path))
    assert count >= 2
